module Juggernaut
  require 'google/apis/calendar_v3'
  require 'google/apis/sheets_v4'
  require 'googleauth'
  require 'googleauth/stores/file_token_store'
  require 'date'
  require 'fileutils'
  require 'json'
  # require 'activites/category'
  # require 'activites/context'
  # require 'activites/day_log'
  # require 'activites/log'
  # require 'analysis/context'
  # require 'analysis/daily_trends_report'
  # require 'analysis/work_time_reporter'
  # require 'executive/context'
  # require 'executive/exporter'
  # require 'executive/reporter'
  # require 'executive/runner'
  require 'google/auth_wrapper'
  require 'google/calendar'
  require 'google/sheets'
  # require 'interface/command_line/context'
  # require 'interface/files/context'
  # require 'interface/command_line'
  # require 'interface/context'
  # require 'maintenance/context'
  # require 'storage/context'
  # require 'storage/trends'
  # require 'tasks/context'
  # require 'toggl/auth'
  # require 'toggl/google_calendar_adapter'
  # require 'toggl/legacy'
  # require 'toggl/report'
  # require 'toggl/time_entry'
  # require 'workflows/calendar_count'
  # require 'workflows/context'
  # require 'workflows/daily'
  # require 'workflows/runner'
  # require 'workflows/weekly'
  # require 'command_line'
  # require 'requests'
  class Whatever
    def self.hello
      puts "HELLO HOLA HI CZESC I W OGOLE"
    end
  end
end
